/**
 * User
 *
 * @module      :: Model
 * @description :: A short summary of how this model works and what it represents.
 * @docs		:: http://sailsjs.org/#!documentation/models
 */

module.exports = {

  // causes only the attributes specified here to be saved to the
	//	database, instead of all items generated by a form.
	schema: true,

  attributes: {
  	
		name : {
			type: 'string',
			required: true
		},
		
		email : {
			type: 'string',
			email: true,
			required: true,
			unique: true
		},
		
		encryptedPassword : {
			type: 'string'
		},
		
		// Filters the values returned when the object is converted to JSON
		toJSON: function() {
			var obj = this.toObject();
			delete obj.password;
			delete obj.confirmation;
			delete obj.encryptedPassword;
			delete obj._csrf;
			return obj;
		},
  }, //attributes

	beforeCreate: function (values, next) {
		// This checks to make sure the password and password confirmation match before creating the record
		if( !values.password || (values.password != values.confirmation) ) {
			return next({err: ["Password doesn't match password confirmation."]});
		}
		
		require('bcrypt').hash(values.password, 10, function passwordEncrypted(err, encryptedPassword) {
			if (err) return next(err);
			values.encryptedPassword = encryptedPassword;
			console.log("encryptedPassword:" + values.encryptedPassword);
			next();
		});
	}
};
